var all_hero = [{
      id: 1,
      name: "敌法师",
      race: ["恶魔猎手"],
      pro: ["精灵"],
      cost: 1,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/antimage_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/antimage_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/antimage_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/antimage_vert.jpg"
    },
    {
      id: 2,
      name: "斧王",
      race: ["战士"],
      pro: ["兽人"],
      cost: 1,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/axe_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/axe_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/axe_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/axe_vert.jpg"
    },
    {
      id: 5,
      name: "水晶室女",
      race: ["法师"],
      pro: ["人类"],
      cost: 2,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/crystal_maiden_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/crystal_maiden_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/crystal_maiden_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/crystal_maiden_vert.jpg"
    },
    {
      id: 6,
      name: "卓尔游侠",
      race: ["猎人"],
      pro: ["亡灵"],
      cost: 1,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/drow_ranger_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/drow_ranger_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/drow_ranger_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/drow_ranger_vert.jpg"
    },
    {
      id: 8,
      name: "剑圣",
      race: ["战士"],
      pro: ["兽人"],
      cost: 2,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/juggernaut_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/juggernaut_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/juggernaut_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/juggernaut_vert.jpg"
    },
    {
      id: 10,
      name: "变体精灵",
      race: ["刺客"],
      pro: ["元素"],
      cost: 2,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/morphling_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/morphling_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/morphling_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/morphling_vert.jpg"
    },
    {
      id: 11,
      name: "影魔",
      race: ["术士"],
      pro: ["恶魔"],
      cost: 3,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/nevermore_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/nevermore_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/nevermore_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/nevermore_vert.jpg"
    },
    {
      id: 13,
      name: "精灵龙",
      race: ["法师"],
      pro: ["精灵", "龙"],
      cost: 2,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/puck_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/puck_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/puck_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/puck_vert.jpg"
    },
    {
      id: 15,
      name: "闪电幽魂",
      race: ["法师"],
      pro: ["元素"],
      cost: 3,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/razor_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/razor_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/razor_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/razor_vert.jpg"
    },
    {
      id: 16,
      name: "沙王",
      race: ["刺客"],
      pro: ["野兽"],
      cost: 3,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/sand_king_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/sand_king_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/sand_king_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/sand_king_vert.jpg"
    },
    {
      id: 19,
      name: "小小",
      race: ["战士"],
      pro: ["元素"],
      cost: 1,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/tiny_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/tiny_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/tiny_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/tiny_vert.jpg"
    },
    {
      id: 21,
      name: "风行者",
      race: ["猎人"],
      pro: ["精灵"],
      cost: 3,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/windrunner_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/windrunner_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/windrunner_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/windrunner_vert.jpg"
    },
    {
      id: 23,
      name: "海军上将",
      race: ["战士"],
      pro: ["人类"],
      cost: 4,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/kunkka_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/kunkka_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/kunkka_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/kunkka_vert.jpg"
    },
    {
      id: 25,
      name: "秀逗魔道士",
      race: ["法师"],
      pro: ["人类"],
      cost: 3,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/lina_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/lina_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/lina_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/lina_vert.jpg"
    },
    {
      id: 27,
      name: "暗影萨满",
      race: ["萨满祭司"],
      pro: ["巨魔"],
      cost: 1,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/shadow_shaman_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/shadow_shaman_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/shadow_shaman_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/shadow_shaman_vert.jpg"
    },
    {
      id: 28,
      name: "鱼人守卫",
      race: ["战士"],
      pro: ["娜迦"],
      cost: 2,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/slardar_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/slardar_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/slardar_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/slardar_vert.jpg"
    },
    {
      id: 29,
      name: "潮汐猎人",
      race: ["猎人"],
      pro: ["娜迦"],
      cost: 5,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/tidehunter_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/tidehunter_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/tidehunter_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/tidehunter_vert.jpg"
    },
    {
      id: 30,
      name: "巫医",
      race: ["术士"],
      pro: ["巨魔"],
      cost: 2,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/witch_doctor_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/witch_doctor_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/witch_doctor_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/witch_doctor_vert.jpg"
    },
    {
      id: 31,
      name: "巫妖",
      race: ["法师"],
      pro: ["亡灵"],
      cost: 5,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/lich_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/lich_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/lich_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/lich_vert.jpg"
    },
    {
      id: 33,
      name: "谜团",
      race: ["术士"],
      pro: ["元素"],
      cost: 5,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/enigma_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/enigma_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/enigma_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/enigma_vert.jpg"
    },
    {
      id: 34,
      name: "修补匠",
      race: ["工匠"],
      pro: ["地精"],
      cost: 1,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/tinker_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/tinker_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/tinker_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/tinker_vert.jpg"
    },
    {
      id: 35,
      name: "狙击手",
      race: ["猎人"],
      pro: ["矮人"],
      cost: 3,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/sniper_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/sniper_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/sniper_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/sniper_vert.jpg"
    },
    {
      id: 36,
      name: "死灵法师",
      race: ["术士"],
      pro: ["亡灵"],
      cost: 4,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/necrolyte_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/necrolyte_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/necrolyte_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/necrolyte_vert.jpg"
    },
    {
      id: 38,
      name: "兽王",
      race: ["猎人"],
      pro: ["兽人"],
      cost: 2,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/beastmaster_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/beastmaster_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/beastmaster_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/beastmaster_vert.jpg"
    },
    {
      id: 39,
      name: "痛苦女王",
      race: ["刺客"],
      pro: ["恶魔"],
      cost: 2,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/queenofpain_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/queenofpain_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/queenofpain_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/queenofpain_vert.jpg"
    },
    {
      id: 40,
      name: "剧毒术士",
      race: ["术士"],
      pro: ["野兽"],
      cost: 3,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/venomancer_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/venomancer_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/venomancer_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/venomancer_vert.jpg"
    },
    {
      id: 44,
      name: "幻影刺客",
      race: ["刺客"],
      pro: ["精灵"],
      cost: 3,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/phantom_assassin_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/phantom_assassin_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/phantom_assassin_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/phantom_assassin_vert.jpg"
    },
    {
      id: 46,
      name: "圣堂刺客",
      race: ["刺客"],
      pro: ["精灵"],
      cost: 4,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/templar_assassin_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/templar_assassin_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/templar_assassin_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/templar_assassin_vert.jpg"
    },
    {
      id: 47,
      name: "冥界亚龙",
      race: ["刺客"],
      pro: ["龙"],
      cost: 3,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/viper_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/viper_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/viper_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/viper_vert.jpg"
    },
    {
      id: 48,
      name: "月之骑士",
      race: ["骑士"],
      pro: ["精灵"],
      cost: 2,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/luna_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/luna_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/luna_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/luna_vert.jpg"
    },
    {
      id: 49,
      name: "龙骑士",
      race: ["骑士"],
      pro: ["人类", "龙"],
      cost: 4,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/dragon_knight_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/dragon_knight_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/dragon_knight_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/dragon_knight_vert.jpg"
    },
    {
      id: 51,
      name: "发条技师",
      race: ["工匠"],
      pro: ["地精"],
      cost: 1,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/rattletrap_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/rattletrap_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/rattletrap_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/rattletrap_vert.jpg"
    },
    {
      id: 53,
      name: "先知",
      race: ["德鲁伊"],
      pro: ["精灵"],
      cost: 2,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/furion_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/furion_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/furion_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/furion_vert.jpg"
    },
    {
      id: 57,
      name: "全能骑士",
      race: ["骑士"],
      pro: ["人类"],
      cost: 3,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/omniknight_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/omniknight_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/omniknight_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/omniknight_vert.jpg"
    },
    {
      id: 58,
      name: "魅惑魔女",
      race: ["德鲁伊"],
      pro: ["野兽"],
      cost: 1,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/enchantress_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/enchantress_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/enchantress_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/enchantress_vert.jpg"
    },
    {
      id: 62,
      name: "赏金猎人",
      race: ["刺客"],
      pro: ["地精"],
      cost: 1,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/bounty_hunter_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/bounty_hunter_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/bounty_hunter_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/bounty_hunter_vert.jpg"
    },
    {
      id: 65,
      name: "蝙蝠骑士",
      race: ["骑士"],
      pro: ["巨魔"],
      cost: 1,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/batrider_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/batrider_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/batrider_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/batrider_vert.jpg"
    },
    {
      id: 69,
      name: "末日使者",
      race: ["战士"],
      pro: ["恶魔"],
      cost: 4,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/doom_bringer_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/doom_bringer_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/doom_bringer_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/doom_bringer_vert.jpg"
    },
    {
      id: 72,
      name: "矮人直升机",
      race: ["工匠"],
      pro: ["矮人"],
      cost: 5,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/gyrocopter_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/gyrocopter_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/gyrocopter_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/gyrocopter_vert.jpg"
    },
    {
      id: 73,
      name: "炼金术士",
      race: ["术士"],
      pro: ["地精"],
      cost: 4,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/alchemist_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/alchemist_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/alchemist_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/alchemist_vert.jpg"
    },
    {
      id: 77,
      name: "狼人",
      race: ["战士"],
      pro: ["人类", "野兽"],
      cost: 3,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/lycan_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/lycan_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/lycan_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/lycan_vert.jpg"
    },
    {
      id: 80,
      name: "德鲁伊",
      race: ["德鲁伊"],
      pro: ["野兽"],
      cost: 4,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/lone_druid_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/lone_druid_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/lone_druid_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/lone_druid_vert.jpg"
    },
    {
      id: 81,
      name: "混沌骑士",
      race: ["骑士"],
      pro: ["恶魔"],
      cost: 2,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/chaos_knight_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/chaos_knight_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/chaos_knight_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/chaos_knight_vert.jpg"
    },
    {
      id: 83,
      name: "树精卫士",
      race: ["德鲁伊"],
      pro: ["精灵"],
      cost: 2,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/treant_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/treant_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/treant_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/treant_vert.jpg"
    },
    {
      id: 84,
      name: "食人魔魔法师",
      race: ["法师"],
      pro: ["食人魔"],
      cost: 1,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/ogre_magi_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/ogre_magi_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/ogre_magi_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/ogre_magi_vert.jpg"
    },
    {
      id: 87,
      name: "干扰者",
      race: ["萨满祭司"],
      pro: ["兽人"],
      cost: 4,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/disruptor_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/disruptor_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/disruptor_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/disruptor_vert.jpg"
    },
    {
      id: 90,
      name: "光之守卫",
      race: ["法师"],
      pro: ["人类"],
      cost: 4,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/keeper_of_the_light_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/keeper_of_the_light_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/keeper_of_the_light_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/keeper_of_the_light_vert.jpg"
    },
    {
      id: 93,
      name: "鱼人夜行者",
      race: ["刺客"],
      pro: ["娜迦"],
      cost: 3,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/slark_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/slark_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/slark_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/slark_vert.jpg"
    },
    {
      id: 94,
      name: "美杜莎",
      race: ["猎人"],
      pro: ["娜迦"],
      cost: 4,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/medusa_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/medusa_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/medusa_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/medusa_vert.jpg"
    },
    {
      id: 95,
      name: "巨魔战将",
      race: ["战士"],
      pro: ["巨魔"],
      cost: 4,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/troll_warlord_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/troll_warlord_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/troll_warlord_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/troll_warlord_vert.jpg"
    },
    {
      id: 98,
      name: "伐木机",
      race: ["工匠"],
      pro: ["地精"],
      cost: 2,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/shredder_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/shredder_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/shredder_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/shredder_vert.jpg"
    },
    {
      id: 100,
      name: "巨牙海民",
      race: ["战士"],
      pro: ["野兽"],
      cost: 1,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/tusk_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/tusk_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/tusk_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/tusk_vert.jpg"
    },
    {
      id: 102,
      name: "死亡骑士",
      race: ["骑士"],
      pro: ["亡灵"],
      cost: 3,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/abaddon_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/abaddon_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/abaddon_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/abaddon_vert.jpg"
    },
    {
      id: 105,
      name: "炸弹人",
      race: ["工匠"],
      pro: ["地精"],
      cost: 5,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/techies_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/techies_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/techies_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/techies_vert.jpg"
    },
    {
      id: 109,
      name: "灵魂守卫",
      race: ["恶魔猎手"],
      pro: ["恶魔"],
      cost: 3,
      url_small_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/terrorblade_sb.png",
      url_large_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/terrorblade_lg.png",
      url_full_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/terrorblade_full.png",
      url_vertical_portrait: "http://cdn.dota2.com/apps/dota2/images/heroes/terrorblade_vert.jpg"
    }
  ],
  all_race = [
    "全选",
    "刺客",
    "工匠",
    "德鲁伊",
    "恶魔猎手",
    "战士",
    "术士",
    "法师",
    "猎人",
    "萨满祭司",
    "骑士"
  ],
  all_pro = [
    "全选",
    "亡灵",
    "人类",
    "元素",
    "兽人",
    "地精",
    "娜迦",
    "巨魔",
    "恶魔",
    "矮人",
    "精灵",
    "野兽",
    "食人魔",
    "龙"
  ],
  all_cost = ["全选", 1, 2, 3, 4, 5];

module.exports = {
  heroList: all_hero,
  raceList: all_race,
  proList: all_pro,
  costList: all_cost
};